from manimlib.imports import *

class CreateCircle(Scene):
    def construct(self):
        circ=Circle(radius=2,color=BLUE)
        #d1=Dot(radius=0.03)
        self.play(GrowFromCenter(circ))
        self.wait(1)
        c1=Arc(radius=2,start_angle=34*PI/18,angle=PI/2)
        c2=Arc(radius=1.155,start_angle=1*PI/18,angle=12*PI/18).shift(0.74*RIGHT+0.89*DOWN)
        c3=Arc(radius=1.155,start_angle=28*PI/18,angle=12*PI/18).shift(0.47*LEFT+1.13*UP)
        c3.rotate(PI)
        circ1=VGroup(c1,c2,c3)        
        #self.play(ShowCreation(circ1))
        #self.wait(2)

        c1=Arc(radius=2,start_angle=25*PI/18,angle=PI/2)
        c2=Arc(radius=1.155,start_angle=28*PI/18,angle=12*PI/18).shift(0.88*LEFT+0.745*DOWN)
        c3=Arc(radius=1.155,start_angle=1*PI/18,angle=12*PI/18).shift(0.74*RIGHT+0.89*DOWN)
        c1.set_fill(BLUE,opacity=1)
        c3.set_fill(BLUE,opacity=1)
        circ5=VGroup(c1,c2,c3) 
        tria1=Polygon(np.array([1.78,-0.35,0]),np.array([0.49,-0.35,0]),np.array([1.2,1.2,0]))
        tria1.rotate(27*PI/18).shift(0.05*LEFT+1.185*DOWN).set_color(BLUE).flip(LEFT).set_fill(BLUE,opacity=1)
        tria2=Polygon(np.array([1.78,-0.35,0]),np.array([0.49,-0.35,0]),np.array([1.25,1.25,0]))
        tria2.rotate(0*PI/18).shift(0.9*LEFT+0.65*DOWN).set_color(BLUE).flip(LEFT).scale(1/5).set_fill(BLUE,opacity=1)
        tria3=Polygon(np.array([1.78,-0.35,0]),np.array([0.4,-0.28,0]),np.array([1.1,1.3,0]))
        tria3.rotate(6*PI/18).shift(1.08*LEFT+1.6*DOWN).set_color(BLUE).flip(LEFT).scale(1/5).set_fill(BLUE,opacity=1)
        tria4=Polygon(np.array([1.78,-0.35,0]),np.array([0.4,-0.28,0]),np.array([1.1,1.3,0]))
        tria4.rotate(4*PI/18).shift(1.01*LEFT+1.48*DOWN).set_color(BLUE).flip(LEFT).scale(1/5).set_fill(BLUE,opacity=1)
        tria=VGroup(tria1,tria2,tria3,tria4)
        circ2=VGroup(circ5,tria)
        #self.play(ShowCreation(circ2))
        #self.wait(2)

        c1=Arc(radius=2,start_angle=16*PI/18,angle=PI/2)
        c2=Arc(radius=1.155,start_angle=1*PI/18,angle=12*PI/18).shift(1.13*LEFT+0.46*DOWN)
        c3=Arc(radius=1.155,start_angle=28*PI/18,angle=12*PI/18).shift(0.88*LEFT+0.745*DOWN)
        c2.rotate(PI)
        circ3=VGroup(c1,c2,c3)        
        #self.play(ShowCreation(circ3))
        #self.wait(2)

        c1=Arc(radius=2,start_angle=7*PI/18,angle=PI/2)
        c2=Arc(radius=1.155,start_angle=28*PI/18,angle=12*PI/18).shift(0.47*LEFT+1.13*UP)
        c3=Arc(radius=1.155,start_angle=1*PI/18,angle=12*PI/18).shift(1.13*LEFT+0.46*DOWN)
        c2.rotate(PI)
        c3.rotate(PI)
        circ4=VGroup(c1,c2,c3)   
        #self.play(ShowCreation(circ4))     
        self.play(ShowCreation(circ1),ShowCreation(circ2),ShowCreation(circ3),ShowCreation(circ4))
        self.wait(1)

        self.play(ApplyMethod(circ1.shift,3*RIGHT+1*UP),ApplyMethod(circ2.shift,3*RIGHT+1*DOWN),ApplyMethod(circ3.shift,3*LEFT+1*DOWN),ApplyMethod(circ4.shift,3*LEFT+1*UP),FadeOut(circ))
        self.wait(1)

        self.play(ApplyMethod(circ1.shift,7.45*LEFT+0.28*UP))
        #self.wait(1)
        self.play(ApplyMethod(circ1.rotate,PI/2))
        self.wait(1)
        self.play(ApplyMethod(circ1.shift,7.45*RIGHT+0.28*DOWN))
        #self.wait(1)
        self.play(ApplyMethod(circ1.rotate,-PI/2))
        self.wait(1)

        self.play(ApplyMethod(circ2.shift,7.2*LEFT+3.72*UP))
        #self.wait(1)
        self.play(ApplyMethod(circ2.rotate,PI))
        self.wait(1)
        self.play(ApplyMethod(circ2.shift,7.2*RIGHT+3.72*DOWN))
        #self.wait(1)
        self.play(ApplyMethod(circ2.rotate,-PI))
        self.wait(1)   

        self.play(ApplyMethod(circ3.shift,0.25*RIGHT+3.45*UP))
        #self.wait(1)
        self.play(ApplyMethod(circ3.rotate,-PI/2))
        self.wait(1)
        self.play(ApplyMethod(circ3.shift,0.25*LEFT+3.45*DOWN))
        #self.wait(1)
        self.play(ApplyMethod(circ3.rotate,PI/2))
        self.wait(1)    
        self.wait(2)

        txt=TextMobject("How many sections of circle are filled =").to_edge(UP)
        self.play(ShowCreation(txt))
        self.wait(1)
        txtt1=TextMobject("1",color=PINK).shift(4*RIGHT+1.8*DOWN)
        self.play(ShowCreation(txtt1))
        self.wait(1)
        self.play(ApplyMethod(txtt1.shift,1*RIGHT+5.12*UP))
        self.wait(1)
        txtt=TextMobject("The total number of sections of circle =").to_edge(DOWN)
        self.play(ShowCreation(txtt))
        self.wait(1)
        txt1=TextMobject("1",color=RED).shift(3.75*RIGHT+1.9*UP)
        txt2=TextMobject("2",color=RED).shift(3.75*RIGHT+1.7*DOWN)
        txt3=TextMobject("3",color=RED).shift(3.75*LEFT*RIGHT+2*DOWN)
        txt4=TextMobject("4",color=RED).shift(3.75*LEFT+1.4*UP)
        self.play(ShowCreation(txt1))
        self.play(ShowCreation(txt2))
        self.play(ShowCreation(txt3))
        self.play(ShowCreation(txt4))
        self.wait(1)
        self.play(FadeOut(txt1),FadeOut(txt2),FadeOut(txt3),ApplyMethod(txt4.shift,8.6*RIGHT+4.7*DOWN))
        self.wait(1)

        self.play(FadeIn(circ),ApplyMethod(circ1.shift,3*LEFT+1*DOWN),ApplyMethod(circ2.shift,3*LEFT+1*UP),ApplyMethod(circ3.shift,3*RIGHT+1*UP),ApplyMethod(circ4.shift,3*RIGHT+1*DOWN))
        self.wait(1)
        txt10=TextMobject("Fraction = ---").next_to(circ)
        self.play(ShowCreation(txt10))
        self.wait(1)
        self.play(FadeOut(txt),FadeOut(txtt),ApplyMethod(txtt1.shift, 3.07*DOWN+0.05*RIGHT),ApplyMethod(txt4.shift,2.92*UP+0.17*RIGHT))
        self.wait(3)
