from manimlib.imports import *

class CreateSquares(Scene):
    def construct(self):
        l1=Polygon(np.array([-1.125,0.375,0]),np.array([-1.125,1.125,0]),color=BLUE)
        l2=Polygon(np.array([-1.875,1.125,0]),np.array([-1.125,1.125,0]),color=BLUE)
        l3=Polygon(np.array([-1.875,1.125,0]),np.array([-1.875,-0.375,0]),color=BLUE)
        l4=Polygon(np.array([-1.875,-0.375,0]),np.array([1.875,-0.375,0]),color=BLUE)
        l5=Polygon(np.array([1.875,-0.375,0]),np.array([1.875,1.125,0]),color=BLUE)
        l6=Polygon(np.array([1.875,1.125,0]),np.array([1.125,1.125,0]),color=BLUE)
        l7=Polygon(np.array([1.125,1.125,0]),np.array([1.125,0.375,0]),color=BLUE)
        l8=Polygon(np.array([-1.125,0.375,0]),np.array([1.125,0.375,0]),color=BLUE)
        l=VGroup(l1,l2,l3,l4,l5,l6,l7,l8)
        self.play(GrowFromCenter(l))
        self.wait(1)

        s1=Square(side_length=0.75,color=BLUE).shift(1.5*LEFT+0.75*UP).set_fill(BLUE,opacity=0.5)
        s2=Square(side_length=0.75,color=BLUE).shift(1.5*LEFT)
        s3=Square(side_length=0.75,color=BLUE).shift(0.75*LEFT)
        s4=Square(side_length=0.75,color=BLUE).set_fill(BLUE,opacity=0.5)
        s5=Square(side_length=0.75,color=BLUE).shift(0.75*RIGHT)
        s6=Square(side_length=0.75,color=BLUE).shift(1.5*RIGHT)
        s7=Square(side_length=0.75,color=BLUE).shift(1.5*RIGHT+0.75*UP).set_fill(BLUE,opacity=0.5)
        sq=VGroup(s1,s2,s3,s4,s5,s6,s7)
        self.play(ShowCreation(sq))
        self.wait(1)

        self.play(FadeOut(l),ApplyMethod(s1.shift,2*LEFT+1.25*UP),ApplyMethod(s2.shift,2*LEFT),ApplyMethod(s3.shift,2.75*LEFT+2*DOWN),ApplyMethod(s5.shift,2.75*RIGHT+2*DOWN),ApplyMethod(s6.shift,2*RIGHT),ApplyMethod(s7.shift,2*RIGHT+1.25*UP))
        self.wait(1)
        self.play(ApplyMethod(s1.shift,3.5*RIGHT),ApplyMethod(s2.shift,3.5*RIGHT),ApplyMethod(s3.shift,3.5*RIGHT),ApplyMethod(s5.shift,3.5*LEFT),ApplyMethod(s6.shift,3.5*LEFT),ApplyMethod(s7.shift,3.5*LEFT))
        self.wait(1)
        self.play(ApplyMethod(s1.shift,2*DOWN),ApplyMethod(s3.shift,2*UP),ApplyMethod(s5.shift,2*UP),ApplyMethod(s7.shift,2*DOWN))
        self.wait(1)
        self.play(ApplyMethod(s1.shift,3.5*LEFT),ApplyMethod(s2.shift,3.5*LEFT),ApplyMethod(s3.shift,3.5*LEFT),ApplyMethod(s5.shift,3.5*RIGHT),ApplyMethod(s6.shift,3.5*RIGHT),ApplyMethod(s7.shift,3.5*RIGHT))
        self.wait(1)
        self.play(ApplyMethod(s1.shift,2*UP),ApplyMethod(s3.shift,2*DOWN),ApplyMethod(s5.shift,2*DOWN),ApplyMethod(s7.shift,2*UP))
        self.wait(1)
        

        txt=TextMobject("How many squares are filled =").to_edge(UP)
        self.play(ShowCreation(txt))
        self.wait(1)
        txt1=TextMobject("1",color=PINK).shift(3.5*LEFT+2*UP)
        txt2=TextMobject("2",color=PINK)
        txtt3=TextMobject("3",color=PINK).shift(3.5*RIGHT+2*UP)
        self.play(ShowCreation(txt1))
        self.play(ShowCreation(txt2))
        self.play(ShowCreation(txtt3))
        self.wait(1)
        self.play(FadeOut(txt1),FadeOut(txt2),ApplyMethod(txtt3.shift,0.25*RIGHT+1.3*UP))
        self.wait(1)

        txtt=TextMobject("The total number of squares =").to_edge(DOWN)
        self.play(ShowCreation(txtt))
        self.wait(1)
        txt1=TextMobject("1",color=RED).shift(3.5*LEFT+2*UP)
        txt2=TextMobject("2",color=RED).shift(3.5*LEFT)
        txt3=TextMobject("3",color=RED).shift(3.5*LEFT+2*DOWN)
        txt4=TextMobject("4",color=RED)
        txt5=TextMobject("5",color=RED).shift(3.5*RIGHT+2*UP)
        txt6=TextMobject("6",color=RED).shift(3.5*RIGHT)
        txt7=TextMobject("7",color=RED).shift(3.5*RIGHT+2*DOWN)
        self.play(ShowCreation(txt1))
        self.play(ShowCreation(txt2))
        self.play(ShowCreation(txt3))
        self.play(ShowCreation(txt4))
        self.play(ShowCreation(txt5))
        self.play(ShowCreation(txt6))
        self.play(ShowCreation(txt7))
        self.wait(1)
        self.play(FadeOut(txt1),FadeOut(txt2),FadeOut(txt3),FadeOut(txt4),FadeOut(txt5),FadeOut(txt6),ApplyMethod(txt7.shift,0.25*RIGHT+1.25*DOWN))
        self.wait(1)
        self.play(FadeIn(l),ApplyMethod(s1.shift,2*RIGHT+1.25*DOWN),ApplyMethod(s2.shift,2*RIGHT),ApplyMethod(s3.shift,2.75*RIGHT+2*UP),ApplyMethod(s5.shift,2.75*LEFT+2*UP),ApplyMethod(s6.shift,2*LEFT),ApplyMethod(s7.shift,2*LEFT+1.25*DOWN))
        self.wait(1)
        txt11=TextMobject("Fraction = --- ").next_to(l)
        self.play(ShowCreation(txt11))
        self.wait(1)
        self.play(FadeOut(txt),FadeOut(txtt),ApplyMethod(txtt3.shift,1.15*RIGHT+2.68*DOWN),ApplyMethod(txt7.shift,1.15*RIGHT+3.275*UP))
        self.wait(2)