from manimlib.imports import *

class CreateRectangle(Scene):
    def construct(self):
        rect=Rectangle(height=2,width=3)
        self.play(GrowFromCenter(rect))
        self.wait(1)
        r1=Rectangle(height=2/3,width=1,color=RED)
        r2=Rectangle(height=2/3,width=1,color=BLUE).shift(1*RIGHT+2/3*UP).set_fill(BLUE,opacity=0.5)
        r3=Rectangle(height=2/3,width=1,color=BLUE).shift(1*RIGHT).set_fill(BLUE,opacity=0.5)
        r4=Rectangle(height=2/3,width=1,color=BLUE).shift(1*RIGHT+2/3*DOWN).set_fill(BLUE,opacity=0.5)
        r5=Rectangle(height=2/3,width=1,color=BLUE).shift(2/3*DOWN).set_fill(BLUE,opacity=0.5)
        r6=Rectangle(height=2/3,width=1,color=BLUE).shift(1*LEFT+2/3*DOWN).set_fill(BLUE,opacity=0.5)
        r7=Rectangle(height=2/3,width=1,color=BLUE).shift(1*LEFT).set_fill(BLUE,opacity=0.5)
        r8=Rectangle(height=2/3,width=1,color=BLUE).shift(1*LEFT+2/3*UP).set_fill(BLUE,opacity=0.5)
        r9=Rectangle(height=2/3,width=1,color=BLUE).shift(2/3*UP).set_fill(BLUE,opacity=0.5)
        self.play(ShowCreation(r1),ShowCreation(r2),ShowCreation(r3),ShowCreation(r4),ShowCreation(r5),ShowCreation(r6),ShowCreation(r7),ShowCreation(r8),ShowCreation(r9))
        self.wait(1)
        self.play(ApplyMethod(r2.shift,2*RIGHT+1*UP),ApplyMethod(r3.shift,2*RIGHT),ApplyMethod(r4.shift,2*RIGHT+1*DOWN),ApplyMethod(r5.shift,1*DOWN),ApplyMethod(r6.shift,2*LEFT+1*DOWN),ApplyMethod(r7.shift,2*LEFT),ApplyMethod(r8.shift,2*LEFT+1*UP),ApplyMethod(r9.shift,1*UP),FadeOut(rect))
        self.wait(2)
        self.play(ApplyMethod(r2.shift,5/3*DOWN),ApplyMethod(r4.shift,5/3*UP),ApplyMethod(r5.shift,5/3*UP),ApplyMethod(r6.shift,5/3*UP),ApplyMethod(r8.shift,5/3*DOWN),ApplyMethod(r9.shift,5/3*DOWN))
        self.wait(1)
        self.play(ApplyMethod(r2.shift,5/3*UP),ApplyMethod(r4.shift,5/3*DOWN),ApplyMethod(r5.shift,5/3*DOWN),ApplyMethod(r6.shift,5/3*DOWN),ApplyMethod(r8.shift,5/3*UP),ApplyMethod(r9.shift,5/3*UP))
        #self.wait(1)
        self.play(ApplyMethod(r2.shift,3*LEFT),ApplyMethod(r3.shift,3*LEFT),ApplyMethod(r4.shift,3*LEFT),ApplyMethod(r6.shift,3*RIGHT),ApplyMethod(r7.shift,3*RIGHT),ApplyMethod(r8.shift,3*RIGHT))
        self.wait(1)
        self.play(ApplyMethod(r2.shift,3*RIGHT),ApplyMethod(r3.shift,3*RIGHT),ApplyMethod(r4.shift,3*RIGHT),ApplyMethod(r6.shift,3*LEFT),ApplyMethod(r7.shift,3*LEFT),ApplyMethod(r8.shift,3*LEFT))
        #self.wait(1)
        self.play(ApplyMethod(r2.shift,3*LEFT+5/3*DOWN),ApplyMethod(r3.shift,3*LEFT),ApplyMethod(r4.shift,3*LEFT+5/3*UP),ApplyMethod(r5.shift,5/3*UP),ApplyMethod(r6.shift,3*RIGHT+5/3*UP),ApplyMethod(r7.shift,3*RIGHT),ApplyMethod(r8.shift,3*RIGHT+5/3*DOWN),ApplyMethod(r9.shift,5/3*DOWN))
        self.wait(1)
        self.play(ApplyMethod(r2.shift,3*RIGHT+5/3*UP),ApplyMethod(r3.shift,3*RIGHT),ApplyMethod(r4.shift,3*RIGHT+5/3*DOWN),ApplyMethod(r5.shift,5/3*DOWN),ApplyMethod(r6.shift,3*LEFT+5/3*DOWN),ApplyMethod(r7.shift,3*LEFT),ApplyMethod(r8.shift,3*LEFT+5/3*UP),ApplyMethod(r9.shift,5/3*UP))
        self.wait(2)
        txt21=TextMobject("The number of filled rectangles =").next_to(r1,11*UP)
        self.play(ShowCreation(txt21))
        self.wait(1)
        txt1=TextMobject("1",color=GREEN).shift(3*RIGHT+5/3*UP)
        txt2=TextMobject("2",color=GREEN).shift(3*RIGHT)
        txt3=TextMobject("3",color=GREEN).shift(3*RIGHT+5/3*DOWN)
        txt4=TextMobject("4",color=GREEN).shift(5/3*DOWN)
        txt5=TextMobject("5",color=GREEN).shift(3*LEFT+5/3*DOWN)
        txt6=TextMobject("6",color=GREEN).shift(3*LEFT)
        txt7=TextMobject("7",color=GREEN).shift(3*LEFT+5/3*UP)
        txt8=TextMobject("8",color=GREEN).shift(5/3*UP)
        self.play(ShowCreation(txt1))
        self.play(ShowCreation(txt2))
        self.play(ShowCreation(txt3))
        self.play(ShowCreation(txt4))
        self.play(ShowCreation(txt5))
        self.play(ShowCreation(txt6))
        self.play(ShowCreation(txt7))
        self.play(ShowCreation(txt8))
        self.wait(1)
        self.play(FadeOut(txt1),FadeOut(txt2),FadeOut(txt3),FadeOut(txt4),FadeOut(txt5),FadeOut(txt6),FadeOut(txt7),ApplyMethod(txt8.shift,4.25*RIGHT+1.7*UP))
        self.wait(1)
        txt22=TextMobject("The total number of rectangles =").next_to(r1,11*DOWN)
        self.play(ShowCreation(txt22))
        self.wait(1)
        txt11=TextMobject("1",color=RED).shift(3*RIGHT+5/3*UP)
        txt12=TextMobject("2",color=RED).shift(3*RIGHT)
        txt13=TextMobject("3",color=RED).shift(3*RIGHT+5/3*DOWN)
        txt14=TextMobject("4",color=RED).shift(5/3*DOWN)
        txt15=TextMobject("5",color=RED).shift(3*LEFT+5/3*DOWN)
        txt16=TextMobject("6",color=RED).shift(3*LEFT)
        txt17=TextMobject("7",color=RED).shift(3*LEFT+5/3*UP)
        txt18=TextMobject("8",color=RED).shift(5/3*UP)
        txt19=TextMobject("9",color=RED)
        self.play(ShowCreation(txt11))
        self.play(ShowCreation(txt12))
        self.play(ShowCreation(txt13))
        self.play(ShowCreation(txt14))
        self.play(ShowCreation(txt15))
        self.play(ShowCreation(txt16))
        self.play(ShowCreation(txt17))
        self.play(ShowCreation(txt18))
        self.play(ShowCreation(txt19))
        self.wait(1)
        self.play(FadeOut(txt11),FadeOut(txt12),FadeOut(txt13),FadeOut(txt14),FadeOut(txt15),FadeOut(txt16),FadeOut(txt17),FadeOut(txt18),ApplyMethod(txt19.shift,4.25*RIGHT+3.25*DOWN))
        self.wait(1)
        self.play(ApplyMethod(r2.shift,2*LEFT+1*DOWN),ApplyMethod(r3.shift,2*LEFT),ApplyMethod(r4.shift,2*LEFT+1*UP),ApplyMethod(r5.shift,1*UP),ApplyMethod(r6.shift,2*RIGHT+1*UP),ApplyMethod(r7.shift,2*RIGHT),ApplyMethod(r8.shift,2*RIGHT+1*DOWN),ApplyMethod(r9.shift,1*DOWN),FadeIn(rect))
        self.wait(1)
        txt10=TextMobject("Fraction = ---").next_to(rect)
        self.play(ShowCreation(txt10))
        self.wait(1)
        self.play(FadeOut(txt21),FadeOut(txt22),ApplyMethod(txt8.shift, 3.05*DOWN+0.25*RIGHT),ApplyMethod(txt19.shift,2.8*UP+0.25*RIGHT))
        self.wait(3)
